[uwsgi]
socket=/code/education/uwsgi_app.sock
chdir = /code/education/
module=education.wsgi:application
master=true
chmod-socket=666
; running as root, consider running as a user. and provide permissions
; uid=www-data
; gid=www-data
vacuum=true


